### ISSUE TITLE
RFC Numbering

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/rfcs#4]
As mentioned here by @DJMcNab, it may be beneficial to number RFCs, and would require little to no effort on the maintainers' side.

https://github.com/bevyengine/rfcs/pull/2#issuecomment-819801084

> It's not just about uniqueness - it's useful for ordering/exploring.
> Like low number RFCs are past and are expected to be somewhat outdated.
> The numbering is assigned based on the GitHub pull request number, which means that
> Ensuring that we increment numbers correctly / avoid collisions
> is easy because GitHub handles it for us

For context, this is @cart's initial comment on RFC numbering:

https://github.com/bevyengine/bevy/pull/1662#issuecomment-816065800

> I don't see much utility in numbering RFCs. We can already reference them via their "github issue number" and their "unique feature name" (which we require in the title). Ensuring that we increment numbers correctly / avoid collisions feels like wasted effort.

**Comment by cart** [comment]
I'm coming around on the "github issue number as prefix in rfc name" idea. I doesn't add much friction and I do like the sorting it gives us.

**Comment by alice-i-cecile** [comment]
This is ~approximately policy now; just need to update the README :)
