### ISSUE TITLE
Accepted and implemented categorization

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/rfcs#8]
It would be nice to be able to tell at a glance which designs still have work to do.

Folders is a decent approach to this, but we could also just use a file prefix.

**Comment by mockersf** [comment]
I think the pull request tracker is a better place to do that, with labels.
That way you get an nice UI with filtering, and keep everything the same

**Comment by alice-i-cecile** [comment]
Do you think we should label accepted RFCs then, and only merge them once they're implemented?

**Comment by bjorn3** [comment]
Rust is using a tracking issue on the rust repo for each rfc (or feature that didn't require a full rfc). This tracking issue tracks the implementation and any blockers to stabilization. Once the feature is stabilized, the tracking issue is closed. It may be a good idea to do something similar for bevy though maybe with closing on full implementation without any issues popping up soon after implementation. Having a tracking issue clearly separates discussion about what and why to implement a feature from discussion about how to implement it internally.

**Comment by cart** [comment]
> tracking issue in bevy repo

I like this a lot. That also allows us to continue treating "merged" RFCs as "accepted", which is the workflow I prefer.

**Comment by cart** [comment]
And yeah I think issues that track a given "category" make sense to me. I'm thinking these should actually live in the main bevy repo, as thats where people are proposing + implementing features (and where we track progress in our roadmap).
