### ISSUE TITLE
Default branch master inconsistent with Bevy default branch main

### ISSUE THREAD

**Issue by Ixentus** [bevyengine/rfcs#9]
The master branch should be renamed to main to be consistent with Bevy's default branch and for the same reasons Bevy changed from master to main.

**Comment by alice-i-cecile** [comment]
Done!

**Comment by NiklasEi** [comment]
Just for the future: there should be a setting in the organisation to have "main" as the default branch for every new repository.

**Comment by cart** [comment]
Hmmm it was already set to this:
![image](https://user-images.githubusercontent.com/2694663/114920841-baf74580-9dde-11eb-8dc4-2d57e9d03ff8.png)

Very weird.

**Comment by cart** [comment]
I just clicked the "update" button. Maybe something was out of sync.
